spring:
  application:
    name: Assignment2
  datasource:
    url: jdbc:mysql://localhost:3308/db?useSSl=false&serverTimezone=Asia/Seoul
    username: root
    password: root1234!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
